

kernel: src/main.rs
	cargo build --release

os.bin: kernel
	#rust-objcopy --strip-all target/riscv64gc-unknown-none-elf/release/os -O binary target/riscv64gc-unknown-none-elf/release/os.bin
	mv target/riscv64gc-unknown-none-elf/release/os target/riscv64gc-unknown-none-elf/release/os.bin

debug: ../bootloader/rustsbi-qemu.bin os.bin
	qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios ../bootloader/rustsbi-qemu.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/release/os.bin,addr=0x80200000 \
    -s -S

run: ../bootloader/rustsbi-qemu.bin os.bin
	qemu-system-riscv64 \
    -machine virt \
    -nographic \
    -bios ../bootloader/rustsbi-qemu.bin \
    -device loader,file=target/riscv64gc-unknown-none-elf/release/os.bin,addr=0x80200000

gdb:
	~/rv64_tools/bin/riscv64-unknown-elf-gdb \
    -ex 'file target/riscv64gc-unknown-none-elf/release/os' \
    -ex 'set arch riscv:rv64' \
    -ex 'target remote localhost:1234'
